#!/bin/sh
chmod 0755 /usr/local/bin/recamera-onvif
chmod 0755 /etc/init.d/K92recamera-onvif
# Gallery apps are started only by sscma-supervisor/appMgr.  An S-prefixed
# script would race it for ownership of the camera at boot.
rm -f /etc/init.d/S92recamera-onvif
exit 0
